version: 2
jobs:
  authenticate:
    docker:
      - image: google/cloud-sdk:198.0.0
    steps:
      - run:
          name: authenticate
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GCLOUD_PROJECT}
  plan:
    docker:
      - image: hashicorp/terraform:0.11.7
    working_directory: ~/cci-terraform
    steps:
      - checkout
      - run:
          name: plan
          command: terraform plan -var-file="prod.tfvars"
  prod_build:
    docker:
      - image: hashicorp/terraform:0.11.7
    working_directory: ~/cci-terraform
    steps:
      - checkout
      - run:
          name: build
          command: terraform apply -var-file="prod.tfvars"

workflows:
  version: 2
  plan-and-build:
    jobs:
      - authenticate
      - plan:
          requires:
            - authenticate
      - prod_build:
          requires:
            - plan
          filters:
            branches:
              only: master
