version: 2
jobs:
  authenticate:
    docker:
      - image: google/cloud-sdk:198.0.0
    steps:
      - run:
          name: authenticate
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
          command: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          command: gcloud --quiet config set project $GCLOUD_PROJECT
  plan:
    docker:
      - image: circleci/terraform:0.11.7
      - image: google/cloud-sdk:198.0.0
        command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GCLOUD_PROJECT
    working_directory: ~/cci-terraform
    steps:
      - checkout
      - run:
          name: plan
          command: |
            echo $GCLOUD_SERVICE_KEY > ~/gcloud-service-key.json
            GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
            terraform init -var-file="prod.tfvars"
            terraform plan -var-file="prod.tfvars"
            terraform apply -var-file="prod.tfvars" -auto-approve
workflows:
  version: 2
  plan-and-build:
    jobs:
      - plan
