version: 2
jobs:
  plan:
    docker:
      - image: hashicorp/terraform:0.11.7
    working_directory: ~/cci-terraform
    steps:
      - checkout
      - run:
          name: plan
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > ~/gcloud-service-key.json
            export GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
            terraform init -var-file="prod.tfvars"
            terraform plan -var-file="prod.tfvars"
            terraform destroy -var-file="prod.tfvars" -auto-approve
workflows:
  version: 2
  plan-and-build:
    jobs:
      - plan
